apiVersion: cluster.cattle.io/v3
kind: MonitorGraph
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: cluster
    component: cluster
  name: cluster-cpu-usage
  namespace: {{ .Values.namespace }}
spec:
  enable: true
  priority: 100
  title: cluster-cpu-usage
  thresholds: 10
  metricsSelector:
    component: cluster
    metric: cpu-usage-seconds-sum-rate
  xAxis:
    show: true
  yAxis:
    show: true
    unit: percent
---
apiVersion: cluster.cattle.io/v3
kind: MonitorGraph
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: cluster
    component: cluster
  name: cluster-cpu-load
spec:
  enable: true
  priority: 101
  title: cluster-cpu-load
  thresholds: 10
  metricsSelector:
    component: cluster
    graph: cpu-load
  xAxis:
    show: true
  yAxis:
    show: true
    unit: number
---
apiVersion: cluster.cattle.io/v3
kind: MonitorGraph
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: cluster
    component: cluster
  name: cluster-memory-usage
spec:
  enable: true
  priority: 102
  title: cluster-memory-usage
  thresholds: 10
  metricsSelector:
    component: cluster
    metric: memory-usage-percent
  xAxis:
    show: true
  yAxis:
    show: true
    unit: percent
---
apiVersion: cluster.cattle.io/v3
kind: MonitorGraph
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: cluster
    component: cluster
  name: cluster-fs-usage-percent
spec:
  enable: true
  priority: 103
  title: cluster-fs-usage-percent
  description: cluster-fs-usage-percent
  thresholds: 10
  metricsSelector:
    component: cluster
    metric: fs-usage-percent
  xAxis:
    show: true
  yAxis:
    show: true
    unit: percent
---
apiVersion: cluster.cattle.io/v3
kind: MonitorGraph
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: cluster
    component: cluster
  name: cluster-disk-io
spec:
  enable: true
  priority: 104
  title: cluster-disk-io
  description: disk-io
  thresholds: 10
  metricsSelector:
    component: cluster
    graph: disk-io
  xAxis:
    show: true
  yAxis:
    show: true
    unit: kbps
---
apiVersion: cluster.cattle.io/v3
kind: MonitorGraph
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: cluster
    component: cluster
  name: cluster-network-io
spec:
  enable: true
  priority: 105
  title: cluster-network-io
  description: node network-io
  thresholds: 10
  metricsSelector:
    component: cluster
    graph: network-io
  xAxis:
    show: true
  yAxis:
    show: true
    unit: kbps
---
apiVersion: cluster.cattle.io/v3
kind: MonitorGraph
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: cluster
    component: cluster
  name: cluster-network-packet
spec:
  enable: true
  priority: 106
  title: cluster-network-packet
  description: node network-packet
  thresholds: 10
  metricsSelector:
    component: cluster
    graph: network-packet
  xAxis:
    show: true
  yAxis:
    show: true
    unit: pps